name: "Workflow"
on: ["pull_request"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: ./
        id: "todo"
        with:
          PROJECTS_SECRET: ${{ secrets.PROJECTS_SECRET }}
